name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 sync --delete --region ap-northeast-1 ./dist/ s3://gha-s3-sample/${{ github.sha }}/
      - name: Create comments
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            最新のDeploy先はこちら！🦈
            [https://gha-s3-sample.s3.ap-northeast-1.amazonaws.com/${{ github.sha }}/index.html](https://gha-s3-sample.s3.ap-northeast-1.amazonaws.com/${{ github.sha }}/index.html)
            